site_name: Paper Playground
site_url: https://phet.colorado.edu/paper-land
nav:
    - Home: index.md
    - Code Documentation: 
      - Board API: use/implementation-notes.md
      - Paper API: use/api.md
    - Paper Tutorial:
      - Camera Setup: tutorial/camera-setup.md
      - Legacy Tutorial: tutorial/tutorial.md
    - Contribution:
      # - How to Contribute: how to make this a redirect
      - Feature Wishlist: contribute/wishlist.md
      # - Community Code of Conduct: how to make this a redirect