[book]
title = "Paper Playground Documentation"
description = "Explore Interaction Design with Paper and JavaScript!"
authors = ["Brett Fiedler", "Jan Paul Posma"]
language = "en"

[rust]
edition = "2023"

[output.html]
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/phetsims/paper-land/tree/master/docs"
edit-url-template = "https://github.com/phetsims/paper-land/edit/master/docs/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
